version: '3.4'
services:
  naming-server:
    build:
      context: naming-server
    ports:
      - "8761:8761"

  test:
    build:
      context: test
    depends_on:
      - naming-server
    ports:
      - "8080:8080"

  frontend:
    build:
      context: frontend
    volumes:
      - ./frontend:/root
    depends_on:
      - naming-server
    ports:
      - "3000:3000"

  nginx:
    build:
      context: nginx
    ports:
      - "443:443"
    depends_on:
      - frontend
