version: '3.4'
services:
  test:
    build:
      context: test
    ports:
      - "8080:8080"

  frontend:
    build:
      context: frontend
    volumes:
      - ./frontend:/root
    ports:
      - "3000:3000"

  nginx:
    build:
      context: nginx
    ports:
      - "443:443"
    depends_on:
      - frontend
