version: '3.4'
services:
  naming-server:
    build:
      dockerfile: ../dockerfiles/JavaAppDockerfile
      context: naming-server
    ports:
      - "8761:8761"

  gateway:
    build:
      dockerfile: ../dockerfiles/JavaAppDockerfile
      context: gateway
    ports:
      - "8080:8080"
    depends_on:
      - naming-server
    environment:
      NAMING_SERVER_ADDRESS: ${NAMING_SERVER_ADDRESS}

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
    - /data/db

  user:
    build:
      dockerfile: ../dockerfiles/JavaAppDockerfile
      context: user
    ports:
      - "8081:8080"
    depends_on:
      - mongo
      - gateway
    environment:
      NAMING_SERVER_ADDRESS: ${NAMING_SERVER_ADDRESS}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}

  frontend:
    build:
      context: frontend
    volumes:
      - ./frontend:/root
    depends_on:
      - gateway
    environment:
      - REACT_APP_GATEWAY_ADDRESS=${GATEWAY_ADDRESS}
    ports:
      - "3000:3000"

  nginx:
    build:
      context: nginx
    ports:
      - "443:443"
    depends_on:
      - frontend
