eureka:
  client:
    serviceUrl:
      defaultZone: ${NAMING_SERVER_ADDRESS}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://USER
          predicates:
            - Path=/user
        - id: user-ws
          uri: lb://USER
          predicates:
            - Path=/ws/users
        - id: baeldung_route
          uri: http://baeldung.com
          predicates:
            - Path=/baeldung/

server:
  ssl:
    enabled: true
    key-alias: gateway-cert
    key-store-password: password
    key-store: classpath:keystore.jks
    key-store-type: JKS