eureka:
  client:
    serviceUrl:
      defaultZone: ${NAMING_SERVER_ADDRESS}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: notifications
          uri: lb://NOTIFICATION-CHANNEL
          predicates:
            - Path=/notification-channel/**
          filters:
            - RewritePath=/notification-channel/(?<segment>.*), /$\{segment}
        - id: user
          uri: lb://USER
          predicates:
            - Path=/user
        - id: user-repository
          uri: lb://USER-REPOSITORY
          predicates:
            - Path=/user-repository
        - id: user-repository-rewrite
          uri: lb://USER-REPOSITORY
          predicates:
            - Path=/user-repository/**
          filters:
            - RewritePath=/user-repository/(?<segment>.*), /user-repository/$\{segment}