eureka:
  client:
    serviceUrl:
      defaultZone: ${NAMING_SERVER_ADDRESS}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://USER
          predicates:
            - Path=/user
        - id: baeldung_route
          uri: http://baeldung.com
          predicates:
            - Path=/baeldung/